export enum QueryType {
    DOMINO = "DOMINO",
    DIRECTION = "DIRECTION",
    PULL = "PULL"
}

export enum MessageType {
    ADD_DOMINO = "ADD_DOMINO",
    PLAYABLE_DOMINOS = "PLAYABLE_DOMINOS",
    HAND = "HAND",
    GAME_START = "GAME_START",
    GAME_OVER = "GAME_OVER",
    ROUND_OVER = "ROUND_OVER",
    PACK_EMPTY = "PACK_EMPTY",
    CLEAR_BOARD = "CLEAR_BOARD",
    SCORES = "SCORES",
    ERROR = "ERROR"
}
